### ISSUE TITLE
Spring Boot 2.1 reports endpoint id as invalid

### ISSUE THREAD

**Issue by fatroom** [zalando/failsafe-actuator#84]
Spring Boot 2.1 added the validation for special characters in endpoint id. 
So when I include failsafe-actuator into the project I'm receiving the following warning in the logs:

```
 Endpoint ID 'circuit-breakers' contains invalid characters, please migrate to a valid format.
```

This caused by change introduced by spring-projects/spring-boot#14840

**Comment by fatroom** [comment]
Not sure what would be the best way of fixing this? 
Change the ID to compliant one (`circuitbreakers`) and release version 2.0 since this seems to be a breaking change? 
Or introduce the second endpoint, with compliant ID and provide the way of graduate migration? (i.e. logging that endpoint with invalid naming should be disabled and discarded?)

**Comment by MALPI** [comment]
I would go for a new version and have a breaking change. Still this is rather minor I'd say.
